version = 1

exclude_patterns = [
  "aecid-testsuite/**",
  "source/root/etc/aminer/template_config.py",
  "source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 140

[[analyzers]]
name = "test-coverage"
enabled = true
