version = 1

exclude_patterns = [
  "aecid-testsuite/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 140

[[analyzers]]
name = "test-coverage"
enabled = true
