# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-PyYAML]
        args: [--install-types, --ignore-missing-imports, --disable-error-code=attr-defined, --implicit-optional]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=140]
      exclude: ^aecid-testsuite/unit/|^aecid-testsuite/system/|^aecid-testsuite/integration/

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    - id: autopep8
      args: [--max-line-length=140, --diff]
      exclude: ^aecid-testsuite/unit/|^aecid-testsuite/system/|^aecid-testsuite/integration/

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    - id: docformatter
      exclude: ^aecid-testsuite/unit/|^aecid-testsuite/system/|^aecid-testsuite/integration/

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    - id: bandit
      exclude: ^aecid-testsuite/

-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.11'
    hooks:
      - id: vulture
