#!/bin/bash -e
# Build script wrapper
#
# How to use:
#
# * Build package only in temporary location _tmpRoot,
#   use it also for storing of temporary files (which should be
#   removed before creating the package). The directory is deleted
#   at the end of the script. By using it that way, no garbage files
#   are left over after building and symlink attacks on temporary
#   directories are prevented.

if [ "${EUID} ${UID}" = "0 0" ] && touch /fake-root-detect 2> /dev/null; then
  rm /fake-root-detect
  echo "Build should not be run as root!" >&2
  exit 1
fi

# Export tmp dir to allow large package builds within vservers
export TMPDIR="/var/tmp"
_projectDir="$(pwd)"

# Use a temporary directory for building, no need to keep it.
_tmpRoot="$(mktemp -d)"
echo "Building package at ${_tmpRoot}" >&2

_debDirectory="${_tmpRoot}/deb-build"
mkdir -- "${_debDirectory}"
cp -a -- "${_projectDir}/source/debian" "${_projectDir}/source/root" "${_debDirectory}"

# Build packages:
# -F: full build
# -us: unsigned sorce
# -uc: unsigned changes
# -sa: force inclusion of original source
(set -e; cd -- "${_debDirectory}"; dpkg-buildpackage -S -us -uc -sa; dpkg-buildpackage -b -uc)
rm -rf -- "${_debDirectory}"
cp -ai -- "${_tmpRoot}/logdata-anomaly-miner_"* .
rm -rf -- "${_tmpRoot}"

echo "Build successful" >&2
