version: "3"

services:
    aminer:
        build:
            context: .
        volumes:
            - '$PWD/akafka:/var/lib/akafka'
            - '$PWD/aminercfg:/etc/aminer'
            - '$PWD/persistency:/var/lib/aminer'
            - '$PWD/logs:/logs'
        depends_on:
                - akafka

    aminer-rest:
