LearnMode: True

Log.StatisticsLevel: 1

Log.DebugLevel: 2

LogResourceList:
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/error.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/error.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/error.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/error.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/other_vhosts_access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/other_vhosts_access.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/other_vhosts_access.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/other_vhosts_access.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/apache2/other_vhosts_access.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/cloud_share/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/inet-firewall/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/internal_share/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/error.log.1'
#  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/error.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/error.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/error.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-access.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-access.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-access.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-access.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-error.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-error.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-error.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/intranet.smith.russellmitchell.com-error.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/apache2/other_vhosts_access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/intranet_server/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/mail/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/vpn/logs/audit/audit.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-access.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-access.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-access.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-access.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-error.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/cloud.smith.russellmitchell.com-error.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/error.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/error.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/error.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/error.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-access.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-access.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-access.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-access.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/mail.smith.russellmitchell.com-error.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/other_vhosts_access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-access.log'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-access.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-access.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-access.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-access.log.4'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-error.log.1'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-error.log.2'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/apache2/proxy-error.log.3'
  - 'file:///home/user/Downloads/AIT-LDS2/russellmitchell/gather/webserver/logs/audit/audit.log'

Parser:
  - id: ApacheAccessParsingModel
    type: ApacheAccessParsingModel
    name: 'apache'

  - id: ApacheErrorParsingModel
    type: ApacheErrorParsingModel
    name: 'apache_error'

  - id: AuditdParsingModel
    type: AuditdParsingModel
    name: 'audit'

  - id: model
    start: True
    type: FirstMatchModelElement
    name: 'model'
    args:
      - ApacheAccessParsingModel
      - ApacheErrorParsingModel
      - AuditdParsingModel

Analysis:
  - type: NewMatchPathValueDetector
    id: apache_client_id_NMPVD
    persistence_id: apache_client_id_NMPVD
    paths:
      - "/model/model/client_ip/client_ip"
      - "/model/model/client_id"
    learn_mode: True

  - type: NewMatchPathValueDetector
    id: apache_user_id_NMPVD
    persistence_id: apache_user_id_NMPVD
    paths:
      - "/model/model/user_id"
    learn_mode: True

  - type: NewMatchPathValueDetector
    id: audit_exe_NMPVD
    persistence_id: audit_exe_NMPVD
    paths:
      - "/model/model/type/service_stop/opt/opt_seq/exe"
    learn_mode: True

  - type: NewMatchPathValueComboDetector
    id: apache_client_user_NMPVCD
    persistence_id: apache_client_user_NMPVCD
    paths:
      - "/model/model/client_id"
      - "/model/model/user_id"
    learn_mode: True

  - type: NewMatchPathValueComboDetector
    id: audit_service_start_uid_exe_NMPVCD
    persistence_id: audit_service_start_uid_exe_NMPVCD
    paths:
      - "/model/model/type/service_start/uid"
      - "/model/model/type/service_start/opt/opt_seq/exe"
    learn_mode: True

  - type: CharsetDetector
    id: audit_msg2_CD
    persistence_id: audit_msg2_CD
    id_path_list:
      - "/model/model/type/user_acct/id"
    paths:
      - "/model/model/type/user_acct/msg2"

  - type: CharsetDetector
    id: apache_user_agent_CD
    persistence_id: apache_user_agent_CD
    id_path_list:
      - "/model/model/client_ip/client_ip"
    paths:
      - "/model/model/combined"

  - type: EntropyDetector
    id: apache_request_version_ED
    persistence_id: apache_request_version_ED
    paths:
      - "/model/model/fm/request/version"

  - type: EntropyDetector
    id: audit_msg2_ED
    persistence_id: audit_msg2_ED
    paths:
      - "/model/model/type/user_acct/msg2"

  - type: ValueRangeDetector
    id: apache_client_ip_VRD
    persistence_id: apache_client_ip_VRD
    paths:
      - "/model/model/client_ip/client_ip/client_ip"

  - type: ValueRangeDetector
    id: audit_user_login_VRD
    persistence_id: audit_user_login_VRD
    paths:
      - "/model/model/type/user_login/time"

  - type: EventFrequencyDetector
    id: apache_status_code_EFD
    persistence_id: apache_status_code_EFD
    window_size: 20
    paths:
      - "/model/model/status_code"

  - type: EventFrequencyDetector
    id: audit_id_EFD
    persistence_id: audit_id_EFD
    window_size: 15
    paths:
      - "/model/model/type/user_start/id"

Input:
  timestamp_paths: [""]
  use_real_time: True
  multi_source: False
  adjust_timestamps: True
  #json_format: True

EventHandlers:
  - id: stpe
    type: StreamPrinterEventHandler
